// <auto-generated />
using System;
using CrudApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace CrudApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("CrudApp.Models.Department", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Code");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("CrudApp.Models.Employee", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateOfBirth");

                    b.Property<string>("DepartmentCode");

                    b.Property<string>("FullName")
                        .IsRequired();

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("RestoreDepartment");

                    b.Property<int>("Salary");

                    b.HasKey("Code");

                    b.HasIndex("DepartmentCode");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("CrudApp.Models.Employee", b =>
                {
                    b.HasOne("CrudApp.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentCode");
                });
#pragma warning restore 612, 618
        }
    }
}
